/*
 * OAuth1TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/11/2016
 */
package com.testwronguri.www;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://www.testwronguri.com";

    //The OAuth token to be set before API calls
    //TODO: Replace the oAuthToken with an appropriate value
    public static String oAuthToken = "TODO: Replace";

    //The OAuth token secret to be set before API calls
    //TODO: Replace the oAuthTokenSecret with an appropriate value
    public static String oAuthTokenSecret = "TODO: Replace";

    //The OAuth client id to be set before API calls
    //TODO: Replace the oAuthClientId with an appropriate value
    public static String oAuthClientId = "TODO: Replace";

    //The OAuth client secret to be set before API calls
    //TODO: Replace the oAuthClientSecret with an appropriate value
    public static String oAuthClientSecret = "TODO: Replace";

}
