/*
 * OAuth1TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/11/2016
 */
package com.testwronguri.www;

import com.testwronguri.www.controllers.*;
import com.testwronguri.www.http.client.HttpClient;

public class OAuth1TesterClient {
    /**
     * Singleton access to Client controller
     * @return	Returns the APIController instance 
     */
    public APIController getClient() {
        return APIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public OAuth1TesterClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public OAuth1TesterClient(String oAuthToken, String oAuthTokenSecret, String oAuthClientId, String oAuthClientSecret) {
        this();
        Configuration.oAuthToken = oAuthToken;
        Configuration.oAuthTokenSecret = oAuthTokenSecret;
        Configuration.oAuthClientId = oAuthClientId;
        Configuration.oAuthClientSecret = oAuthClientSecret;
    }
}