/*
 * OAuth1TesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 on 07/11/2016
 */
package com.testwronguri.www.controllers;

import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.rules.Timeout;

import com.testwronguri.www.OAuth1TesterClient;
import com.testwronguri.www.Configuration;
import com.testwronguri.www.testing.HttpCallBackCatcher;


/**
 * Base class for all test cases
 */
public class ControllerTestBase {
    /**
     * Test configuration
     */
    public final static int REQUEST_TIMEOUT = 30;

    public final static double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures
     */
    
    // Used to serve as HttpCallBack and to capture request & response
    protected HttpCallBackCatcher httpResponse = new HttpCallBackCatcher();
    
    /**
     * Setup test
     */
    @Before
    public void setUp() throws Exception {
        httpResponse = new HttpCallBackCatcher(); 
    }

    /**
     * Tear down test
     */
    @After
    public void tearDown() throws Exception {
        if(httpResponse.getResponse() != null)
            httpResponse.getResponse().shutdown();
        httpResponse = null;
    }
    
    // Singleton instance of client for all test classes
    private static OAuth1TesterClient client;
    private static Object clientSync = new Object();
    
    /**
     * Get client instance
     * @return
     */
    protected static OAuth1TesterClient getClient() {
        if(client == null)
            synchronized (clientSync) {
                client = new OAuth1TesterClient();
            }
        return client;
    }

    /**
     * Apply test configuration
     */
    protected static void applyConfiguration() {
        // Set Configuration parameters for test execution
        Configuration.baseUri = "http://apimatic.hopto.org:3000";
        Configuration.oAuthToken = "nnch734d00sl2jdk";
        Configuration.oAuthTokenSecret = "pfkkdhi9sl3r4s00";
        Configuration.oAuthClientId = "dpf43f3p2l4k3l03";
        Configuration.oAuthClientSecret = "kd94hf93k423kf44";
    }
}
